[build]  base = "frontend"  command = "npm run build"  publish = ".next"[build.environment]  NEXT_PUBLIC_API_URL = "https://mini-ecommerce-18ps.onrender.com/api"  NODE_VERSION = "18"[[plugins]]  package = "@netlify/plugin-nextjs"

# Handle Next.js routing - redirect all requests to Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true

# Fallback for static assets
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Special rule for public assets
[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200
